<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wt_spamshield_formhandler"
 *
 * Auto generated by Extension Builder 2014-05-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Spamshield for FormHandler',
	'description' => 'Integrates wt_spamshield with formhandler.',
	'category' => 'services',
	'author' => 'Charles Brunet',
	'author_email' => 'charles@cbrunet.net',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '4.7.0-6.2.99',
			'wt_spamshield' => '1.2.0-1.2.99',
			'formhandler' => '1.7.0-2.0.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
